---
  - name: create idm installation script
    copy: src=idm-install dest=/usr/local/bin/ mode=770

  - name: install idm base packages
    yum: name={{ item }} state=present
    with_items:
      - vim-enhanced
      - tmux
      - openssh-clients
      - expect 
      - ntp
      - ipa-server-dns
      - ipa-server
      - bind 
      - bind-dyndb-ldap

  - name: check version
    shell: "rpm -q python2-pyasn1"
    register: version

  - name: force downgrade
    shell: "yum downgrade -y python2-pyasn1"
    when: version.stdout == "python2-pyasn1-0.3.7-2.el7rhgs.noarch"

...
