- name: Terminate tagged instances
  hosts: tag_Name_packer_host
  gather_facts: false
  remote_user: ec2-user
  vars_files:
     - vars.yaml
  tasks:
    - meta: refresh_inventory
    - ec2:
        state: absent
        region: "{{ region }}" 
        instance_ids: "{{ ec2_id }}"
      delegate_to: localhost

