---

- hosts: default

  roles:
    - { role: instructor-user, tags: ['instructor-user']}
    - { role: registered-host, tags: ['registered-host']}
    - { role: idm-install, tags: ['idm-install']}
  tasks:
    - name: unsubscribe system
      redhat_subscription: state=absent

...
